name: inflearn_lecture
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  go_router: ^4.3.0
  flutter_riverpod: ^2.0.0-dev.9
  flutter_secure_storage: ^6.0.0
  json_annotation: ^4.6.0
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  skeletons: ^0.0.3
  badges: ^2.0.3
  uuid: ^3.0.6
  debounce_throttle: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3+1


flutter:
  uses-material-design: true

  assets:
    - asset/img/misc/
    - asset/img/food/
    - asset/img/logo/
    - asset/svg/icon/
    - asset/rive/

  fonts:
    - family: NotoSans
      fonts:
        - asset: asset/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: asset/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: asset/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: asset/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: asset/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: asset/fonts/NotoSansKR-Thin.otf
          weight: 100